name 'ama-ssh-private-keys'
maintainer 'AMA Team'
maintainer_email 'ops@amagroup.ru'
source_url 'https://github.com/ama-team/cookbook-ssh-private-keys'
issues_url 'https://github.com/ama-team/cookbook-ssh-private-keys/issues'
license 'mit'
description 'Installs/Configures ama-ssh-private-keys'
long_description 'Installs/Configures ama-ssh-private-keys'
version '0.1.0'
